import bear1 from './cards/bear1.jpg'
import beetle1 from './cards/beetle1.jpg'
import lynx1 from './cards/lynx1.jpg'
import fox1 from './cards/fox1.jpg'
import goldfish1 from './cards/goldfish1.jpg'
import tanuki1 from './cards/tanuki1.jpg'
import boar1 from './cards/boar1.jpg'
import weasel1 from './cards/weasel1.jpg'
import rabbit1 from './cards/rabbit1.jpg'
import doe1 from './cards/doe1.jpg'
import hummingbird1 from './cards/hummingbird1.jpg'
import bee1 from './cards/bee1.jpg'
import monkey1 from './cards/monkey1.jpg'
import owl1 from './cards/owl1.jpg'
import bear2 from './cards/bear2.jpg'
import beetle2 from './cards/beetle2.jpg'
import lynx2 from './cards/lynx2.jpg'
import fox2 from './cards/fox2.jpg'
import goldfish2 from './cards/goldfish2.jpg'
import tanuki2 from './cards/tanuki2.jpg'
import boar2 from './cards/boar2.jpg'
import weasel2 from './cards/weasel2.jpg'
import rabbit2 from './cards/rabbit2.jpg'
import doe2 from './cards/doe2.jpg'
import hummingbird2 from './cards/hummingbird2.jpg'
import bee2 from './cards/bee2.jpg'
import monkey2 from './cards/monkey2.jpg'
import owl2 from './cards/owl2.jpg'
import bear3 from './cards/bear3.jpg'
import beetle3 from './cards/beetle3.jpg'
import lynx3 from './cards/lynx3.jpg'
import fox3 from './cards/fox3.jpg'
import goldfish3 from './cards/goldfish3.jpg'
import tanuki3 from './cards/tanuki3.jpg'
import boar3 from './cards/boar3.jpg'
import weasel3 from './cards/weasel3.jpg'
import rabbit3 from './cards/rabbit3.jpg'
import doe3 from './cards/doe3.jpg'
import hummingbird3 from './cards/hummingbird3.jpg'
import bee3 from './cards/bee3.jpg'
import monkey3 from './cards/monkey3.jpg'
import owl3 from './cards/owl3.jpg'
import bear4 from './cards/bear4.jpg'
import beetle4 from './cards/beetle4.jpg'
import lynx4 from './cards/lynx4.jpg'
import fox4 from './cards/fox4.jpg'
import goldfish4 from './cards/goldfish4.jpg'
import tanuki4 from './cards/tanuki4.jpg'
import boar4 from './cards/boar4.jpg'
import weasel4 from './cards/weasel4.jpg'
import rabbit4 from './cards/rabbit4.jpg'
import doe4 from './cards/doe4.jpg'
import hummingbird4 from './cards/hummingbird4.jpg'
import bee4 from './cards/bee4.jpg'
import monkey4 from './cards/monkey4.jpg'
import owl4 from './cards/owl4.jpg'
import hedgehog from './cards/hedgehog.jpg'
import caterpillar from './cards/caterpillar.jpg'
import flamingo from './cards/flamingo.jpg'
import ram from './cards/ram.jpg'
import wolf from './cards/wolf.jpg'
import lemur from './cards/lemur.jpg'
import squirrel from './cards/squirrel.jpg'
import turtle from './cards/turtle.jpg'
import coati from './cards/coati.jpg'
import racoon from './cards/racoon.jpg'
import beaver from './cards/beaver.jpg'
import raven from './cards/raven.jpg'
import bat from './cards/bat.jpg'
import parrot from './cards/parrot.jpg'
import meerkat from './cards/meerkat.jpg'
import horse from './cards/horse.jpg'
import axolotls from './cards/axolotls.jpg'
import chimpanzee from './cards/chimpanzee.jpg'
import toucan from './cards/toucan.jpg'
import butterfly from './cards/butterfly.jpg'
import spider from './cards/spider.jpg'
import hippopotamus from './cards/hippopotamus.jpg'
import eagleowl from './cards/eagleowl.jpg'
import woodpecker from './cards/woodpecker.jpg'
import badger from './cards/badger.jpg'
import rooster from './cards/rooster.jpg'
import rhinoceros from './cards/rhinoceros.jpg'
import goat from './cards/goat.jpg'
import bull from './cards/bull.jpg'
import lizard from './cards/lizard.jpg'
import frog from './cards/frog.jpg'
import marmot from './cards/marmot.jpg'
import platypus from './cards/platypus.jpg'
import crane from './cards/crane.jpg'
import sloth from './cards/sloth.jpg'
import koala from './cards/koala.jpg'
import leopard from './cards/leopard.jpg'
import eagle from './cards/eagle.jpg'
import snake from './cards/snake.jpg'
import cricket from './cards/cricket.jpg'
import panther from './cards/panther.jpg'
import gorilla from './cards/gorilla.jpg'
import bison from './cards/bison.jpg'
import chameleon from './cards/chameleon.jpg'
import crocodile from './cards/crocodile.jpg'
import elephant from './cards/elephant.jpg'
import dolphin from './cards/dolphin.jpg'
import dog from './cards/dog.jpg'
import panda from './cards/panda.jpg'
import stag from './cards/stag.jpg'
import tapir from './cards/tapir.jpg'
import varan from './cards/varan.jpg'

import tree3A from './trees/tree3A.png'
import tree3B from './trees/tree3B.png'
import tree4A from './trees/tree4A.png'
import tree4B from './trees/tree4B.png'
import tree5A from './trees/tree5A.png'
import tree5B from './trees/tree5B.png'
import tree6 from './trees/tree6.png'
import tree7 from './trees/tree7.png'
import tree8 from './trees/tree8.png'
import tree9 from './trees/tree9.png'
import tree10 from './trees/tree10.png'
import tree11 from './trees/tree11.png'
import forestBack from './forestBack.jpg'
import autumnBack from './autumnBack.jpg'
import autumnBackGreen from './autumnBackGreen.png'
import autumnVerso from './autumnVerso.jpg'
import autumnCases from './autumnCases.png'
import autumnSpirit1 from './autumnSpirit1.png'
import autumnSpirit2 from './autumnSpirit2.png'
import autumnToken1 from './autumnToken1.png'
import autumnToken2 from './autumnToken2.png'
import autumnToken3 from './autumnToken3.png'
import autumnSpiritCircle from './autumnSpiritCircle.png'


import summerVerso from './summerVerso.jpg'
import summerSpiritCircle from './summerSpiritCircle.png'

import winterVerso from './winterVerso.jpg'
import winterSpiritCircle from './winterSpiritCircle.png'

import springVerso from './springVerso.jpg'
import springSpiritCircle from './springSpiritCircle.png'

import circleOfSpirits from './circleOfSpirits.png'
import sun from './resources/sun.png'
import drop from './resources/drop.png'
import seed from './resources/seed.png'
import wind from './resources/wind.png'
import sacredFlower from './resources/sacredFlower.png'
import gregarious from './resources/gregarious.png'
import fragment from './fragment.png'
import fire2 from './fire2.png'
import fire3 from './fire3.png'
import fire4 from './fire4.png'
import firstPlayer from './firstPlayer.png'





import sampleImage from './cards/verso1.jpg'

const Images = {
  sampleImage, bear1, beetle1, lynx1, fox1, goldfish1, tanuki1, boar1, weasel1, rabbit1, doe1, hummingbird1, bee1, monkey1, owl1,
  bear2, beetle2, lynx2, fox2, goldfish2, tanuki2, boar2, weasel2, rabbit2, doe2, hummingbird2, bee2, monkey2, owl2,
  bear3, beetle3, lynx3, fox3, goldfish3, tanuki3, boar3, weasel3, rabbit3, doe3, hummingbird3, bee3, monkey3, owl3,
  bear4, beetle4, lynx4, fox4, goldfish4, tanuki4, boar4, weasel4, rabbit4, doe4, hummingbird4, bee4, monkey4, owl4,
  hedgehog, caterpillar, flamingo, ram, wolf, lemur, squirrel, turtle, coati, racoon, beaver, raven, bat, parrot, meerkat, horse, axolotls,
  chimpanzee, toucan, butterfly, spider, hippopotamus, eagleowl, woodpecker, badger, rooster, rhinoceros, goat, bull, lizard, frog, marmot,
  platypus, crane, sloth, koala, leopard, eagle, snake, cricket, panther, gorilla, bison, chameleon, crocodile, elephant, dolphin, dog, panda,
  stag, tapir, varan,
  tree3A, tree3B, tree4A, tree4B, tree5A, tree5B, tree6, tree7, tree8, tree9, tree10, tree11,
  forestBack,
  autumnVerso, autumnBack, autumnBackGreen, autumnCases, autumnSpirit1, autumnSpirit2, autumnToken1, autumnToken2, autumnToken3, autumnSpiritCircle,
  summerVerso, summerSpiritCircle, 
  winterVerso, winterSpiritCircle,
  springVerso, springSpiritCircle, 
  circleOfSpirits,
  sun, drop, seed, wind, sacredFlower, gregarious,
  fragment, fire2, fire3, fire4,
  firstPlayer
}

export default Images