import { isEnumValue } from '@gamepark/rules-api'

enum GuardianAnimal {
  BearWinter = 1,
  BeetleWinter,
  LynxWinter,
  FoxWinter,
  GoldfishWinter,
  TanukiWinter,
  BoarWinter,
  WeaselWinter,
  HareWinter,
  FawnWinter,
  HummingbirdWinter,
  BeeWinter,
  BaboonWinter,
  OwlWinter,
  Hedgehog,
  Caterpillar,
  Flamingo,
  Ram,
  Wolf,
  Lemur,
  Squirrel,
  Tortoise,
  Coati,
  Racoon,
  Beaver,
  Raven,
  Bat,
  Cockatoo,
  Meerkat,
  Horse,
  Axolotl,
  Chimpanzee,
  Toucan,
  Butterfly,
  Spider,
  Hippopotamus,
  HornedOwl,
  Woodpecker,
  Badger,
  Rooster,
  Rhinoceros,
  Goat,
  Bull,
  Salamander,
  Frog,
  Marmot,
  Platypus,
  Crane,
  Loris,
  Koala,
  Leopard,
  Eagle,
  Cobra,
  Cricket,
  Panther,
  Gorilla,
  Bison,
  Chameleon,
  Crocodile,
  Elephant,
  Dolphin,
  Dog,
  Panda,
  Stag,
  Tapir,
  FireVaran,

  Anteater = 101,
  Ara,
  Armadillo,
  Capybara,
  Crayfish,
  FlyingSquirrel,
  Koi,
  Peafowl,
  Sloth,
  Tiger,
  KodamaWinter,
  KodamaSpring,
  KodamaSummer,
  KodamaAutumn,
  KodamaTree1,
  KodamaTree2,
  KodamaTree3,
  KodamaTree4,
  KodamaTree5,
  KodamaTree6,
  KodamaWater1,
  KodamaWater2,
  KodamaWater3,
  KodamaWater4,
  KodamaWater5,
  KodamaWater6,
  KodamaFlower1,
  KodamaFlower2,
  KodamaFlower3,
  KodamaFlower4,
  KodamaFlower5,
  KodamaFlower6,

  BearSpring = 201,
  BeetleSpring,
  LynxSpring,
  FoxSpring,
  GoldfishSpring,
  TanukiSpring,
  BoarSpring,
  WeaselSpring,
  HareSpring,
  FawnSpring,
  HummingbirdSpring,
  BeeSpring,
  BaboonSpring,
  OwlSpring,

  BearSummer = 301,
  BeetleSummer,
  LynxSummer,
  FoxSummer,
  GoldfishSummer,
  TanukiSummer,
  BoarSummer,
  WeaselSummer,
  HareSummer,
  FawnSummer,
  HummingbirdSummer,
  BeeSummer,
  BaboonSummer,
  OwlSummer,

  BearAutumn = 401,
  BeetleAutumn,
  LynxAutumn,
  FoxAutumn,
  GoldfishAutumn,
  TanukiAutumn,
  BoarAutumn,
  WeaselAutumn,
  HareAutumn,
  FawnAutumn,
  HummingbirdAutumn,
  BeeAutumn,
  BaboonAutumn,
  OwlAutumn,
}

export const guardianAnimals = Object.values(GuardianAnimal).filter(isEnumValue)
export const startingGuardianAnimalsSpring = guardianAnimals.filter((g) => g >= GuardianAnimal.BearSpring && g <= GuardianAnimal.OwlSpring).concat(GuardianAnimal.KodamaSpring)
export const startingGuardianAnimalsSummer = guardianAnimals.filter((g) => g >= GuardianAnimal.BearSummer && g <= GuardianAnimal.OwlSummer).concat(GuardianAnimal.KodamaSummer)
export const startingGuardianAnimalsAutumn = guardianAnimals.filter((g) => g >= GuardianAnimal.BearAutumn && g <= GuardianAnimal.OwlAutumn).concat(GuardianAnimal.KodamaAutumn)
export const startingGuardianAnimalsWinter = guardianAnimals.filter((g) => g >= GuardianAnimal.BearWinter && g <= GuardianAnimal.OwlWinter).concat(GuardianAnimal.KodamaWinter)

export const isVaran = (guardianAnimal: GuardianAnimal) => GuardianAnimal.FireVaran === guardianAnimal

export default GuardianAnimal
