import CardType from './CardType'
import GuardianAnimal from './GuardianAnimal'
import {
    Axolotl,
    Baboon,
    Badger,
    Bat,
    Bear,
    Beaver,
    Bee,
    Beetle,
    Bison,
    Boar,
    Bull,
    Butterfly,
    Caterpillar,
    Chameleon,
    Chimpanzee,
    Coati,
    Cobra,
    Cockatoo,
    Crane,
    Cricket,
    Crocodile,
    Dog,
    Dolphin,
    Eagle,
    Elephant,
    Fawn,
    FireVaran,
    Flamingo,
    Fox,
    Frog,
    Goat,
    Goldfish,
    Gorilla,
    Hare,
    Hedgehog,
    Hippopotamus,
    HornedOwl,
    Horse,
    Hummingbird,
    Koala,
    Lemur,
    Leopard,
    Lynx,
    Marmot,
    Meerkat,
    Owl,
    Panda,
    Panther,
    Platypus,
    Racoon,
    Ram,
    Raven,
    Rhinoceros,
    Rooster,
    Salamander,
    Sloth,
    Spider,
    Squirrel,
    Stag,
    Tanuki,
    Tapir,
    Tortoise,
    Toucan,
    Weasel,
    Wolf,
    Woodpecker
} from './GuardiansAnimals'
import Resource from './Resource'


type GuardianAnimalDetails = {
    resources: { [key in Resource]?: number }
    cost: number
    type?: CardType
}

export default GuardianAnimalDetails

export const GuardianAnimalDescriptions: Record<GuardianAnimal, GuardianAnimalDetails> = {
    [GuardianAnimal.BearWinter]: Bear,
    [GuardianAnimal.BeetleWinter]: Beetle,
    [GuardianAnimal.LynxWinter]: Lynx,
    [GuardianAnimal.FoxWinter]: Fox,
    [GuardianAnimal.GoldfishWinter]: Goldfish,
    [GuardianAnimal.TanukiWinter]: Tanuki,
    [GuardianAnimal.BoarWinter]: Boar,
    [GuardianAnimal.WeaselWinter]: Weasel,
    [GuardianAnimal.HareWinter]: Hare,
    [GuardianAnimal.FawnWinter]: Fawn,
    [GuardianAnimal.HummingbirdWinter]: Hummingbird,
    [GuardianAnimal.BeeWinter]: Bee,
    [GuardianAnimal.BaboonWinter]: Baboon,
    [GuardianAnimal.OwlWinter]: Owl,
    [GuardianAnimal.Hedgehog]: Hedgehog,
    [GuardianAnimal.Caterpillar]: Caterpillar,
    [GuardianAnimal.Flamingo]: Flamingo,
    [GuardianAnimal.Ram]: Ram,
    [GuardianAnimal.Wolf]: Wolf,
    [GuardianAnimal.Lemur]: Lemur,
    [GuardianAnimal.Squirrel]: Squirrel,
    [GuardianAnimal.Tortoise]: Tortoise,
    [GuardianAnimal.Coati]: Coati,
    [GuardianAnimal.Racoon]: Racoon,
    [GuardianAnimal.Beaver]: Beaver,
    [GuardianAnimal.Raven]: Raven,
    [GuardianAnimal.Bat]: Bat,
    [GuardianAnimal.Cockatoo]: Cockatoo,
    [GuardianAnimal.Meerkat]: Meerkat,
    [GuardianAnimal.Horse]: Horse,
    [GuardianAnimal.Axolotl]: Axolotl,
    [GuardianAnimal.Chimpanzee]: Chimpanzee,
    [GuardianAnimal.Toucan]: Toucan,
    [GuardianAnimal.Butterfly]: Butterfly,
    [GuardianAnimal.Spider]: Spider,
    [GuardianAnimal.Hippopotamus]: Hippopotamus,
    [GuardianAnimal.HornedOwl]: HornedOwl,
    [GuardianAnimal.Woodpecker]: Woodpecker,
    [GuardianAnimal.Badger]: Badger,
    [GuardianAnimal.Rooster]: Rooster,
    [GuardianAnimal.Rhinoceros]: Rhinoceros,
    [GuardianAnimal.Goat]: Goat,
    [GuardianAnimal.Bull]: Bull,
    [GuardianAnimal.Salamander]: Salamander,
    [GuardianAnimal.Frog]: Frog,
    [GuardianAnimal.Marmot]: Marmot,
    [GuardianAnimal.Platypus]: Platypus,
    [GuardianAnimal.Crane]: Crane,
    [GuardianAnimal.Loris]: Sloth,
    [GuardianAnimal.Koala]: Koala,
    [GuardianAnimal.Leopard]: Leopard,
    [GuardianAnimal.Eagle]: Eagle,
    [GuardianAnimal.Cobra]: Cobra,
    [GuardianAnimal.Cricket]: Cricket,
    [GuardianAnimal.Panther]: Panther,
    [GuardianAnimal.Gorilla]: Gorilla,
    [GuardianAnimal.Bison]: Bison,
    [GuardianAnimal.Chameleon]: Chameleon,
    [GuardianAnimal.Crocodile]: Crocodile,
    [GuardianAnimal.Elephant]: Elephant,
    [GuardianAnimal.Dolphin]: Dolphin,
    [GuardianAnimal.Dog]: Dog,
    [GuardianAnimal.Panda]: Panda,
    [GuardianAnimal.Stag]: Stag,
    [GuardianAnimal.Tapir]: Tapir,
    [GuardianAnimal.FireVaran]: FireVaran,

    [GuardianAnimal.BearSpring]: Bear,
    [GuardianAnimal.BeetleSpring]: Beetle,
    [GuardianAnimal.LynxSpring]: Lynx,
    [GuardianAnimal.FoxSpring]: Fox,
    [GuardianAnimal.GoldfishSpring]: Goldfish,
    [GuardianAnimal.TanukiSpring]: Tanuki,
    [GuardianAnimal.BoarSpring]: Boar,
    [GuardianAnimal.WeaselSpring]: Weasel,
    [GuardianAnimal.HareSpring]: Hare,
    [GuardianAnimal.FawnSpring]: Fawn,
    [GuardianAnimal.HummingbirdSpring]: Hummingbird,
    [GuardianAnimal.BeeSpring]: Bee,
    [GuardianAnimal.BaboonSpring]: Baboon,
    [GuardianAnimal.OwlSpring]: Owl,

    [GuardianAnimal.BearSummer]: Bear,
    [GuardianAnimal.BeetleSummer]: Beetle,
    [GuardianAnimal.LynxSummer]: Lynx,
    [GuardianAnimal.FoxSummer]: Fox,
    [GuardianAnimal.GoldfishSummer]: Goldfish,
    [GuardianAnimal.TanukiSummer]: Tanuki,
    [GuardianAnimal.BoarSummer]: Boar,
    [GuardianAnimal.WeaselSummer]: Weasel,
    [GuardianAnimal.HareSummer]: Hare,
    [GuardianAnimal.FawnSummer]: Fawn,
    [GuardianAnimal.HummingbirdSummer]: Hummingbird,
    [GuardianAnimal.BeeSummer]: Bee,
    [GuardianAnimal.BaboonSummer]: Baboon,
    [GuardianAnimal.OwlSummer]: Owl,

    [GuardianAnimal.BearAutumn]: Bear,
    [GuardianAnimal.BeetleAutumn]: Beetle,
    [GuardianAnimal.LynxAutumn]: Lynx,
    [GuardianAnimal.FoxAutumn]: Fox,
    [GuardianAnimal.GoldfishAutumn]: Goldfish,
    [GuardianAnimal.TanukiAutumn]: Tanuki,
    [GuardianAnimal.BoarAutumn]: Boar,
    [GuardianAnimal.WeaselAutumn]: Weasel,
    [GuardianAnimal.HareAutumn]: Hare,
    [GuardianAnimal.FawnAutumn]: Fawn,
    [GuardianAnimal.HummingbirdAutumn]: Hummingbird,
    [GuardianAnimal.BeeAutumn]: Bee,
    [GuardianAnimal.BaboonAutumn]: Baboon,
    [GuardianAnimal.OwlAutumn]: Owl,
} as Record<GuardianAnimal, GuardianAnimalDetails> // TODO remove this cast once all Kodama card are implemented

export function countSolitary(animals: GuardianAnimal[]): number {
    return animals.reduce((sum, animal) => sum + ((GuardianAnimalDescriptions[animal].type == CardType.Solitary) ? 1 : 0), 0)
}
export function countGregarious(animals: GuardianAnimal[]): number {
    return animals.reduce((sum, animal) => sum + ((GuardianAnimalDescriptions[animal].type == CardType.Gregarious) ? 1 : 0), 0)
}
export function getSolitaryGregariousDifference(animals: GuardianAnimal[]): number {
    return countSolitary(animals) - countGregarious(animals)
}