export const cardHeight = 22
export const cardWith = cardHeight * 65 / 100
export const treeHeight = 14
export const treeWith = treeHeight
export const discardLeft = 23
export const discardTop = 57
export const playDrawTop = 60
export const playDrawLeft = 23
export const casesWidth = 120
export const casesHeight = casesWidth * 66 / 100
export const casesTop = -7
export const casesLeft = 38
export const spiritImage1Height = 25
export const spiritImage1Width = spiritImage1Height * 76 / 100
export const spiritImage2Height = 40
export const spiritImage2Width = spiritImage2Height * 55 / 100
export const panelHeight = 15
export const panelWidth = panelHeight * 2.2
export const panelLeft = 10
export const panelBottom = 0.1
export const spiritTokenWidth = 14
export const spiritTokenHeight = spiritTokenWidth * 66 / 100
export const helpLineTop = 60
export const helpLineLeft = 39
export const circleOfSpiritsTop = 15
export const circleOfSpiritsLeft = 95
export const reserveTop = 2
export const reserveLeft = 10
export const reserveStacksTop = 13
export const reserveStacksLeft = 0
export const reserveCardHeight = 22
export const reserveCardWith = reserveCardHeight * 65 / 100
export const reserveRowDrawTop = 13
export const reserveRowDrawLeft = 16
export const reserveRowCardHeight = 22
export const reserveRowCardWith = reserveCardHeight * 65 / 100
export const resourceTop = 2
export const resourceLeft = 0
export const disperserTop = -2
export const disperserLeft = 0
export const fragmentTop = 20
export const fragmentLeft = 160
export const fireTop = 20
export const fireLeft = 30
export const fireHeight = 8
export const fireWith = fireHeight * 74 / 100
export const rockTop = 8
export const rockLeft = 33
export const rockHeight = 6
export const rockWith = 9