export const cardHeight = 20
export const cardWith = cardHeight * 65 / 100
export const playDrawTop = 57
export const discardLeft = 23
export const discardTop = 57
export const playDrawLeft = 23
export const casesWidth = 95
export const casesHeight = casesWidth * 66 / 100
export const casesTop = 1
export const casesLeft = 42
export const spiritImage1Height = 25
export const spiritImage1Width = spiritImage1Height * 76 / 100
export const spiritImage2Height = 25
export const spiritImage2Width = spiritImage2Height * 55 / 100
export const panelHeight = 15
export const panelWidth = panelHeight * 2.2
export const panelLeft = 10
export const panelBottom = 0.1
export const spiritTokenWidth = 10
export const spiritTokenHeight = spiritTokenWidth * 66 / 100
