export enum LocationType {
  Table = 1,
  ForestBoard,
  CircleOfSpiritBoardSpace,
  PlayerDeckStack,
  PlayerDiscardStack,
  ReserveStack,
  ReserveRow,
  ProtectiveTreeDeck,
  VictoryTileArea,
  VaranDeck,
  FragmentStack,
  HelpLine,
  FireStack,
  CircleOfSpiritBoardFire,
}